### ISSUE TITLE
python-3.11 wheels ?

### ISSUE THREAD

**Issue by stonebig** [3-manifolds/SnapPy#102]
a new release with python-3.11 wheels would be awesome, unless there is pypi wheel size issue ?

**Comment by NathanDunfield** [comment]
Our aim is to release SnapPy 3.1 with wheels for Python 3.11 in the next couple weeks.  I'll leave this issue open until we do so, so you'll get notification when it's ready.

**Comment by NathanDunfield** [comment]
SnapPy 3.1 has been released and Python 3.11 wheels for all supported platforms have been posted on PyPI.
