### ISSUE TITLE
mktemp is obsolete, use mkstemp with 'ppm' as suffix

### ISSUE THREAD

**Issue by unhyperbolic** [3-manifolds/SnapPy#16]
https://github.com/3-manifolds/SnapPy/blob/7c1ea66f413a3ec759d82a50a1744a056a36b846/python/gui.py#L91

There are two problems with this line: mkstemp or tempfile.TemporaryFile is favored over mktemp. 'ppm' shouldn't be added after the temporary file is created but passed as "suffix = '.ppm'" to the function.

**Comment by culler** [comment]
Fixed in [18ec953](https://github.com/3-manifolds/SnapPy/commit/18ec953e48f7193c990c6adf6ce14561d010d0e6).
