### ISSUE TITLE
move headers to a subdirectory

### ISSUE THREAD

**Issue by dimpase** [3-manifolds/SnapPy#21]
https://trac.sagemath.org/ticket/31180 points at a case where one has a conflict with `[Dd]irichlet.h`, 
see also https://github.com/fredrik-johansson/arb/issues/239#issuecomment-756002174
(which also unfortunately squats the precious header namespace)

**Comment by NathanDunfield** [comment]
Sorry, I'm not quite sure what you mean here.  SnapPy does not install any header files, and in the source tree they are in a subdirectory.  The problem noted in https://trac.sagemath.org/ticket/31180 is caused by homebrew's misconfigured Python, cf. https://trac.sagemath.org/ticket/31132 .
