### ISSUE TITLE
The snappy_manifold method of Mcomplex does not work in Python 3

### ISSUE THREAD

**Issue by MarkCBell** [3-manifolds/SnapPy#7]
In Python 3, running
```
>>> from snappy.snap.t3mlite import Mcomplex
>>> Mcomplex('4_1').snappy_manifold()
```
results in 
```
ModuleNotFoundError: No module named 'StringIO'
```
due to an `import StringIO` in `snap/t3mlite/mcomplex.py` which does not work in Python 3 as this module was renamed to `io`. This was tested in Python 3.7.0 with SnapPy 2.7

**Comment by NathanDunfield** [comment]
Closed in f610f5b7e17d7c5b6a7847682229c97c7fa18afc.  Thanks for the report!
