### ISSUE TITLE
App: Error when opening python scripts that contain multiline functions

### ISSUE THREAD

**Issue by NathanDunfield** [3-manifolds/SnapPy#86]
Using `File -> Open` with on a file containing exactly:
```
def foo(x):
    a = x + 1
    return x
```
results in 
```
In[14]:     return x
  Input In [14]
    return x
    ^
SyntaxError: 'return' outside function
```

**Comment by culler** [comment]
I think this may be fixed in my latest commit (36cdc23).

**Comment by NathanDunfield** [comment]
Agreed, closed by 36cdc23713ad14a82266ad3ca7a8c897b48d81f9.

**Comment by fchapoton** [comment]
so the issue can be closed ?

**Comment by culler** [comment]
Yes.

**Comment by fchapoton** [comment]
Thanks. Do you have any time to have a look at my pull request ?
